micronaut:
  application:
    name: inventory
  server:
    port: 8081
consul:
  client:
    registration:
      enabled: true
    default-zone:
    - "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
        